# Generated by Django 4.2.6 on 2023-10-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=240, verbose_name='Product Name')),
                ('productOwnerName', models.CharField(max_length=240, verbose_name='Product Owner Name')),
                ('developers', models.CharField(max_length=240, verbose_name='Developers')),
                ('scrumMasterName', models.CharField(max_length=240, verbose_name='Scrum Master Name')),
                ('startDate', models.DateField(auto_now_add=True, verbose_name='Start Date')),
                ('methodology', models.CharField(max_length=240, verbose_name='Methodology')),
                ('location', models.CharField(max_length=240, verbose_name='Location')),
            ],
        ),
    ]
